from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

from io_utils import ensure_dir, read_json, write_json, write_text


def export_playwright_specs(input_path: str, output_dir: str) -> dict:
    payload = read_json(input_path)
    cases = payload.get("test_cases") or payload.get("cases") or []
    if not cases:
        raise ValueError("Input test-cases JSON must contain a non-empty 'test_cases' or 'cases' array.")

    grouped: dict[str, list[dict]] = {}
    for case in cases:
        if not case.get("automation_candidate", True):
            continue
        slug = derive_group_slug(case)
        grouped.setdefault(slug, []).append(case)

    destination = ensure_dir(output_dir)
    generated_files: list[str] = []

    for slug in sorted(grouped):
        group_cases = sorted(grouped[slug], key=lambda item: item.get("test_case_id", ""))
        content = render_spec_file(group_title(group_cases[0], slug), group_cases)
        filename = f"{slug}.spec.ts"
        write_text(destination / filename, content)
        generated_files.append(filename)

    manifest = {
        "project_name": payload.get("project_name", "Generated Playwright Specs"),
        "generated_files": generated_files,
        "test_count": sum(len(items) for items in grouped.values()),
    }
    write_json(destination / "playwright-specs-manifest.json", manifest)
    return manifest


def derive_group_slug(case: dict) -> str:
    feature = str(case.get("feature", "")).strip()
    if feature:
        return slugify(feature)

    requirement_ids = case.get("requirement_ids") or []
    if requirement_ids:
        prefix = str(requirement_ids[0]).split("-")[0]
        if prefix:
            return slugify(prefix)

    match = re.match(r"TC-([A-Z0-9]+)-", str(case.get("test_case_id", "")))
    if match:
        return slugify(match.group(1))
    return "general"


def group_title(case: dict, fallback_slug: str) -> str:
    feature = str(case.get("feature", "")).strip()
    if feature:
        return feature
    return fallback_slug.replace("-", " ").title()


def slugify(value: str) -> str:
    normalized = re.sub(r"[^a-z0-9]+", "-", value.strip().lower())
    collapsed = re.sub(r"-{2,}", "-", normalized).strip("-")
    return collapsed or "general"


def render_spec_file(group_name: str, cases: list[dict]) -> str:
    sections = [
        "// Generated by requirements-qa-orchestrator.",
        "// These are starter Playwright Test artifacts and are intentionally skipped until selectors and assertions are implemented.",
        "",
        "import { test } from '@playwright/test';",
        "",
        f"test.describe('{escape_ts(group_name)}', () => {{",
    ]
    for case in cases:
        sections.append(indent(render_case_block(case)))
    sections.append("});")
    sections.append("")
    return "\n".join(sections)


def render_case_block(case: dict) -> str:
    title = f"{case.get('test_case_id', '')} - {case.get('title', 'Generated case')}".strip()
    lines = [
        f"test('{escape_ts(title)}', async ({{ page }}) => {{",
        "  test.skip(true, 'Starter artifact generated by requirements-qa-orchestrator. Implement selectors and assertions before enabling.');",
        "",
        f"  // Requirement IDs: {', '.join(case.get('requirement_ids') or []) or 'None'}",
        f"  // Priority: {case.get('priority', 'Medium')}",
        f"  // Type: {case.get('type', 'Functional')}",
    ]

    preconditions = case.get("preconditions") or []
    if preconditions:
        lines.append("  // Preconditions:")
        lines.extend([f"  // - {item}" for item in preconditions])

    steps = case.get("steps") or []
    for step in steps:
        lines.extend(
            [
                "",
                f"  await test.step('{escape_ts(step)}', async () => {{",
                f"    // TODO: implement step: {escape_ts(step)}",
                "  });",
            ]
        )

    expected_results = case.get("expected_results") or []
    if expected_results:
        lines.extend(["", "  // Expected results:"])
        lines.extend([f"  // - {item}" for item in expected_results])

    lines.extend(["", "  // TODO: add assertions matching the expected results.", "});", ""])
    return "\n".join(lines)


def indent(block: str, prefix: str = "  ") -> str:
    return "\n".join(prefix + line if line else "" for line in block.splitlines())


def escape_ts(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "\\'")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Export grouped starter Playwright .spec.ts files from canonical test-cases JSON."
    )
    parser.add_argument("--input", required=True, help="Path to canonical test-cases.json")
    parser.add_argument("--output-dir", required=True, help="Directory to write generated .spec.ts files")
    args = parser.parse_args()
    summary = export_playwright_specs(args.input, args.output_dir)
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
